# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install jq
    - name: Declare variables
      id: vars
      shell: bash
      run: |
        branch=$(echo ${GITHUB_REF#refs/heads/})
        sha_short=$(git rev-parse --short HEAD)
        package_name=$(jq -r '.name' <package.json)
        package_version=$(jq -r '.version' <package.json)
        echo "package_name=${package_name}" >> env
        echo "package_version=${package_version}" >> env
        echo "sha_short=${sha_short}" >> env
        echo "bundle_name=${package_name}-v${package_version}-${sha_short}-${branch}-${{ matrix.node-version }}.tar.gz" >> $GITHUB_ENV
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm clean-install
    - run: npm run build --if-present
    - run: npm test
    - name: Bundle for the deployment
      run: |
        tar cfz ${{ env.bundle_name }} *
    - uses: actions/upload-artifact@master
      with:
        name: Bundling artifacts
        path: ${{ env.bundle_name }}
